### ISSUE TITLE
Display images that do not contain photosphere metadata as flat images

### ISSUE THREAD

**Issue by vanitasvitae** [McPhysix/Spherical#6]
This could either be done using a seperate view (ImageView for example), or by a different Renderobject/projection type.

**Comment by sleistikow** [comment]
An ImageView definitely is the best solution here in terms of implementation complexity and efficiency.

**Comment by vanitasvitae** [comment]
I propose to use this library: https://github.com/davemorrissey/subsampling-scale-image-view

**Comment by vanitasvitae** [comment]
Implemented.
