### ISSUE TITLE
Display progress indicator when loading an image

### ISSUE THREAD

**Issue by vanitasvitae** [McPhysix/Spherical#9]
Currently the app just displays a white screen. It would be nice to have a loading animation/progressbar instead.

**Comment by sleistikow** [comment]
As mentioned earlier, implementing a (percentage) progress bar is impossible (See #13).
Instead, a loading animation should work just fine.

**Comment by vanitasvitae** [comment]
Yeah, thats basically what I meant. Both loading circles and percentage bars are represented by the ProgressBar class in Android :)

**Comment by vanitasvitae** [comment]
Implemented
